### ISSUE TITLE
Does qwen2.5-coder support function calling?

### ISSUE THREAD

**Issue by Muuut** [QwenLM/Qwen2.5-Coder#180]
According to the documentation, I use VLLM to build a openai compatible server for qwen2.5-coder-7b-instruct.

That is my code
```
messages = [
    {
        "role": "user",
        "content": "Calculate how many r's are in the word 'strawberry'"
    }
]

# Define the tools
tools = [{
    "type": "function",
    "function": {
        "name": "execute_python",
        "description": "Execute python code in a Jupyter notebook cell and return result",
        "parameters": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "description": "The python code to execute in a single cell"
                }
            },
            "required": ["code"]
        }
    }
}]

# Generate text with OpenAI
response = client.chat.completions.create(
    model="qwen2.5-7B-coder",
    messages=messages,
    tools=tools,
)
```

However, I got this:
![屏幕截图 2024-11-26 124247](https://github.com/user-attachments/assets/7ee58f03-ebd2-4226-862e-8feaee1f1a9f)
The finish_reason is "stop" instead of "tool_calls", and the tool_calls is empty.
So I wonder whether qwen2.5-coder series support function calling?

**Comment by sagarey** [comment]
same problem recurred on Qwen2.5-Coder-32B-instruct deployed by vllm, while Qwen2.5-32B-instruct support function calling as expected.

**Comment by Muuut** [comment]
> same problem recurred on Qwen2.5-Coder-32B-instruct deployed by vllm, while Qwen2.5-32B-instruct support function calling as expected.

I did not set the ```system content``` in the message before. After setting, function calling works normally.

**Comment by sagarey** [comment]
> > same problem recurred on Qwen2.5-Coder-32B-instruct deployed by vllm, while Qwen2.5-32B-instruct support function calling as expected.
> 
> I did not set the `system content` in the message before. After setting, function calling works normally.

Default qwen system prompt? I tried it, and still the problem that tool_calls is empty and content returns tool call string. Whether it is Qwen2.5-Coder-32B-instruct or Qwen2.5-Coder-7B-instruct, without any adjustments, only model  switch to Qwen2.5-32B-instruct or Qwen2.5-7B-instruct can tool_calls be obtained correctly.

**Comment by sagarey** [comment]
When Qwen2.5-Coder deployed with Ollama, it can return tool_calls as expected.

**Comment by huang-jl** [comment]
Same problem as @ethal0n on vllm with Qwen2.5-Coder-3B-Instruct, with the same prompt/messages as [documentation](https://qwen.readthedocs.io/en/latest/framework/function_call.html#vllm).

**Comment by huang-jl** [comment]
I have read the code of Qwen-Agent and vLLM about their function calling logic. I find that vLLM uses the [nous](https://github.com/QwenLM/Qwen-Agent/blob/c0349d064a1924866788ab9aa04a4e4ecea8d041/qwen_agent/llm/function_calling.py#L20) or [hermes](https://docs.vllm.ai/en/latest/features/tool_calling.html#hermes-models-hermes) style. However, in your links to [Qwen-Agent](https://github.com/QwenLM/Qwen-Agent/blob/main/examples/function_calling.py), it uses 'qwen' by default. Actually, I think it is the old function calling template that [Qwen2 support](https://qwen.readthedocs.io/en/latest/framework/function_call.html#qwen2-function-calling-template) instead of [Qwen2.5 function call template](https://qwen.readthedocs.io/en/latest/framework/function_call.html#qwen2-5-function-calling-templates).

(In short, I think the Qwen2.5-Coder models should support newest hermes-style template, which is supported in vLLM. If Qwen2.5-Coder models only support its Qwen-2 style template, then it explains why it support in Qwen-Agent but not in vLLM).

So what's value of `fncall_prompt_type` passed [here](https://github.com/QwenLM/Qwen-Agent/blob/c0349d064a1924866788ab9aa04a4e4ecea8d041/examples/function_calling.py#L29) in your code when using Qwen-Agent, @ethal0n ?

**Comment by huang-jl** [comment]
Thanks for you quick reply. When using Qwen-Agent, you need to pass an argument  called `fncall_prompt_type`. For example (this is copied from your links about [Qwen-Agent](https://github.com/QwenLM/Qwen-Agent/blob/main/examples/function_calling.py)):

```python
llm = get_chat_model({
        # Use the model service provided by DashScope:
        'model': 'qwen2.5-72b-instruct',
        'model_server': 'dashscope',
        'api_key': os.getenv('DASHSCOPE_API_KEY'),
        'generate_cfg': {
            'fncall_prompt_type': fncall_prompt_type # NOTE HERE!!!
        },
    })
```

Do you pass this argument, or what is the value you pass, when you make the coder models works with function calling?

**Comment by huang-jl** [comment]
That make sense. I think the conclusions of this issue are:


1. The function calling does not works for Qwen2.5 coder models, because it does not support [hermes-style](https://docs.vllm.ai/en/latest/features/tool_calling.html#hermes-models-hermes) function calling.
2. The function calling works for normal Qwen2.5 models (e.g., Qwen2.5-14B-Instruct) in vLLM, as in Qwen [docs](https://qwen.readthedocs.io/en/latest/framework/function_call.html#vllm).
3. The function calling works for coder models in Qwen-Agent. Since Qwen-Agent by default uses [Qwen2-style](https://qwen.readthedocs.io/en/latest/framework/function_call.html#qwen2-function-calling-template) function calling. This Qwen2-style is not support in vLLM, but is supported by the Qwen2.5 coder model.

I think maybe Qwen2.5 coder models does not trained the dataset with hermes-style function calling as normal Qwen2.5 models. If you would like to use the function call in vLLM:

1. Use normal Qwen2.5 models (this is most easy method).
2. Write a tool call parser for vLLM (you can refer to [here](https://github.com/vllm-project/vllm/blob/7a3a83e3b87f50fe9c0985a5c5bcc1d4cf2e95cd/vllm/entrypoints/openai/tool_parsers/hermes_tool_parser.py#L23)), which parse the LLM output according to the Qwen2-style.
3. Uses Qwen-Agent with the built-in support for Qwen2-style.

**Comment by WinPooh32** [comment]
Found working [trick](https://github.com/ollama/ollama/blob/66fb8575ced090a969c9529c88ee57a8df1259c2/tools/template.go#L13) for Ollama: replace `<tool_call>` by `[tool_call]` at the model template.

**Comment by larock22** [comment]
> Found working [trick](https://github.com/ollama/ollama/blob/66fb8575ced090a969c9529c88ee57a8df1259c2/tools/template.go#L13) for Ollama: replace `<tool_call>` by `[tool_call]` at the model template.

i was going insane thank you brother this worked for me

**Comment by Gabrielsv01** [comment]
> Found working [trick](https://github.com/ollama/ollama/blob/66fb8575ced090a969c9529c88ee57a8df1259c2/tools/template.go#L13) for Ollama: replace `<tool_call>` by `[tool_call]` at the model template.

Solved!

Thank you!

I was having the same problem trying to integrate with picoclaw.

this worked for me:

```
# 1. Extract the current Modelfile from your model.
ollama show qwen2.5-coder:7b --modelfile > Modelfile

# 2. Edit the file and replace it.<tool_call> to [tool_call]
# In template, find to:
#   <tool_call>
# and change to:
#   [tool_call]

# Use sed or vim:
sed -i 's/<tool_call>/[tool_call]/g' Modelfile
sed -i 's/<\/tool_call>/[\/tool_call]/g' Modelfile

# 3.Recreate the model using the modified template.
ollama create qwen-picoclaw-fixed -f Modelfile

# 4. Test
curl -s http://10.0.0.142:11434/v1/chat/completions -H "Content-Type: application/json" -d '{
  "model": "qwen-picoclaw-fixed",
  "messages": [{"role": "user", "content": "What is the temperature in New York?"}],
  "stream": false,
  "tools": [
    {
      "type": "function",
      "function": {
        "name": "get_temperature",
        "description": "Get the current temperature for a city",
        "parameters": {
          "type": "object",
          "required": ["city"],
          "properties": {
            "city": {"type": "string", "description": "The name of the city"}
          }
        }
      }
    }
  ]
}'

```
