### ISSUE TITLE
关于 CrossCodeEval 测试

### ISSUE THREAD

**Issue by yfzhou3993** [QwenLM/Qwen2.5-Coder#181]
你好：
       请问在 CrossCodeEval 测试中，具体使用的测试脚本是 CrossCodeEval 开源的脚本吗，也就是这个地址的脚本 https://github.com/amazon-science/cceval
       如果是自定义的脚本，请问该脚本方便开源吗，最近在复现Qwen2.5 Coder的测试结果。
       
       非常感谢！

**Comment by cyente** [comment]
我们基本follow了这个脚本，但是对于序列长度、后处理、以及special tokens的设置略有修改。我们的评测脚本正在整理中，很快就会开出来。请稍等2天。

**Comment by cyente** [comment]
https://github.com/QwenLM/Qwen2.5-Coder/tree/main/qwencoder-eval/base/benchmarks/fim-bench

hi, all the code completion benchmark (except safim) are released here. hoping to hear your feedback.

**Comment by yfzhou3993** [comment]
hi，我尝试了最新公开的测试脚本，成功复现了报告中的测试结果。非常感谢！

关于在 CrossCodeEval 上的测试，仍然有两个小问题想要咨询一下：
1. CrossCodeEval 原本是一个 `left2right` 类型的测试任务，这里作为一个 `FIM` 测试任务的考量是什么呢
2. 另外，我看到在具体测试时，`crossfile_context` 是放在 `suffix` 中的 `right_context` 后的位置，和报告中 repo-level pretrain的数据格式并不一致，请问这样的测试格式是出于什么考虑呢

非常感谢您的耐心回复

**Comment by cyente** [comment]
1. The official data of CrossCodeEval provides suffix content, and since our goal here is to evaluate the model's FIM (Fill-In-Middle) capability, we have organized it into FIM format. However, if you only want to evaluate left-to-right generation, that would be fine too.

2. We believe that an excellent model should be able to handle any test format, so we haven't deliberately tried to standardize the test format with the training format. Currently, all test formats  in the repolevel-FIM section uniformly follow the latest academic paper. You can refer to https://github.com/amazon-science/Repoformer/tree/main for more details.

**Comment by wapleeeeee** [comment]
@cyente 您好，感谢您的回答，我这里也用提供的代码复现了结果。
这里想问下 Qwen2.5 系列（非 Coder）遵循这种训练和推理方式吗，我尝试了一下用相同的方式评测 Qwen2.5-7B-Instruct，得到的分数很低。

**Comment by cyente** [comment]
没遵循

**Comment by wapleeeeee** [comment]
@cyente 我根据这篇论文 https://arxiv.org/pdf/2207.14255
尝试了一下把 psm 修改成 spm 的形式，发现掉点比较严重，想问下当前只兼容 psm 的形式

**Comment by cyente** [comment]
是的，建议采用PSM格式
